---
abstract: 'What you need to develop with Mite'
author:
  - unknown
build_requires:
  Fennec: '2.016'
  Test::Compile: '0.24'
  Test::Deep: '0.110'
  Test::Most: '0.31'
  Test::Sims: '20130412'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mite-Compiler
provides:
  Mite::Attribute:
    file: lib/Mite/Attribute.pm
  Mite::Class:
    file: lib/Mite/Class.pm
  Mite::Compiled:
    file: lib/Mite/Compiled.pm
  Mite::Compiler:
    file: lib/Mite/Compiler.pm
    version: v0.0.1
  Mite::Project:
    file: lib/Mite/Project.pm
  Mite::Source:
    file: lib/Mite/Source.pm
requires:
  Method::Signatures: '20140224'
  Mite: v0.0.1
  Mouse: '1.08'
  Path::Tiny: '0.052'
  perl: v5.10.1
  version: '0.77'
resources:
  bugtracker: https://github.com/evalEmpire/Mite/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/evalEmpire/Mite
version: v0.0.1
