---
abstract: 'Moose-like OO with no dependencies'
author:
  - unknown
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mite
provides:
  Mite:
    file: lib/Mite.pm
    version: v0.0.1
recommends:
  Class::XSAccessor: '1.17'
requires:
  perl: v5.10.1
  version: '0.77'
resources:
  bugtracker: https://github.com/evalEmpire/Mite/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/evalEmpire/Mite
version: v0.0.1
